### ISSUE TITLE
Docker tag

### ISSUE THREAD

**Issue by deimosfr** [lesmyrmidons/ansible-role-docker#2]
Hi,

I suggest that you add docker tags to help on deploying only docker part. Example:

``` yaml
- name: Add repository for debian wheesy
  apt_repository: repo='deb http://http.debian.net/debian wheezy-backports main' update_cache=yes
  when: ansible_distribution_release == 'wheezy'
  tags: docker
```

Thanks
